modcluster/mod_proxy_cluster

- native/mod_manager/mod_manager.c
- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
* some basic optimizations on command processing
* modernizing the old codebase and housekeeping
> Commands processing optimizations.

- native/mod_manager/mod_manager.c
I'm porting this change from 1.3.x into master so that it isn't lost.
> maintenance on mod_manager functions

- native/mod_manager/domain.c
Additional porting from 1.2.x
See [pull 208](https://github.com/modcluster/mod_cluster/pull/208).
Formerly in 1.2.x: [pull 190](https://github.com/modcluster/mod_cluster/pull/190)
> Vol. II Command processing optimizations in domain.c

- native/mod_proxy_cluster/mod_proxy_cluster.c
See https://issues.jboss.org/browse/MODCLUSTER-522
> Fix for MODCLUSTER-522 + gcc code fix.

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.jboss.org/browse/MODCLUSTER-550
> MODCLUSTER-550 Failover targets should be chosen deterministically

- native/include/node.h
- native/mod_manager/mod_manager.c
https://issues.jboss.org/browse/MODCLUSTER-420
> MODCLUSTER-420 Drop support for httpd older than 2.4: mod_manager

- native/include/node.h
- native/mod_proxy_cluster/mod_proxy_cluster.c
> Fix for https://issues.jboss.org/browse/MODCLUSTER-582

- native/include/balancer.h
- native/include/context.h
- native/include/domain.h
- native/include/host.h
- native/include/node.h
- native/include/sessionid.h
- native/mod_proxy_cluster/mod_proxy_cluster.c
clean some warnings and remove support for httpd-2.2.x
> Clean warning and 2.2.x support defines.

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.jboss.org/browse/JBCS-634
> [JBCS-634] decrease loops per vhosts for balancer changes

- native/include/mod_proxy_cluster.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
All IPv6 in [...] format in fact were broken :-(
> Fix for https://issues.redhat.com/browse/MODCLUSTER-717, 718 and 719

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
That removes the messup with the good mod_proxy default values.
> Fix for MODCLUSTER-721

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Note that it requires http://people.apache.org/~covener/patches/wstunnel-decline.diff to be merged in httpd.
> Fix for https://issues.redhat.com/browse/MODCLUSTER-722

- native/mod_proxy_cluster/mod_proxy_cluster.c
up stream fix for https://github.com/modcluster/mod_cluster/pull/500
https://issues.redhat.com/browse/MODCLUSTER-722
> The fix for MODCLUSTER-722 was incomplete, mod_cluster was coring on failover

- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix for https://issues.redhat.com/browse/MODCLUSTER-733
> remove the http worker creation as trunk doesn't require it any more.

- native/balancers/mod_lbmethod_cluster.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Use the right #if thanks: ylavic.dev@gmail.com
> Fix for MODCLUSTER-761

- native/mod_proxy_cluster/mod_proxy_cluster.c
Improve proxy_cluster_post_request locking
> Fix for https://issues.redhat.com/browse/MODCLUSTER-758

- native/advertise/mod_advertise.c
- native/balancers/mod_lbmethod_cluster.c
- native/common/common.c
- native/mod_cluster_slotmem/mod_sharedmem.c
- native/mod_cluster_slotmem/sharedmem_util.c
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix for signed/unsigned comparison and a few pointer related warnings.
> Fix some compile warnings

- native/balancers/mod_lbmethod_cluster.c
- native/common/common.c
- native/mod_cluster_slotmem/sharedmem_util.c
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
While going through the codebase I've noticed that there are some formatting inconsistencies. This PR tries to fix that.
It fixes things like different spacing for cycles, around operators, etc. There is no functional change.
> Fix code formatting inconsistency

- native/include/mod_proxy_cluster.h
- native/include/node.h
- native/mod_cluster_slotmem/sharedmem_util.c
- native/mod_manager/balancer.c
- native/mod_manager/context.c
- native/mod_manager/domain.c
- native/mod_manager/host.c
- native/mod_manager/mod_manager.c
- native/mod_manager/node.c
- native/mod_manager/sessionid.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Arrange the logic to fix [MODCLUSTER-774]
https://issues.redhat.com/browse/MODCLUSTER-774
notes:
The locking logic is a lot simpler now and we will able to remove our own slot_mem logic
Most of the ap_assert(0) will be replace by a graceful restart of the child process.
> Arrange the logic to fix [MODCLUSTER-774]

- test/native/Dockerfile
- test/native/Makefile
- test/native/README.md
- test/native/files/context.xml
- test/native/httpd/Dockerfile
- test/native/httpd/README.md
- test/native/httpd/mod_proxy_cluster.conf
- test/native/includes/miniserver.py
- test/native/pom.xml
- test/native/tests.sh
I went through the test suite and made some changes. Mainly
* change formatting of `tests.sh` script, renamed some functions, and fixed bugs
* updated httpd container image used in tests (it was not working)
* updated README
There is space for more improvements, mainly separating individual tests to be able to run them separately, but that's something for the future.
> Test suite improvements

- .github/workflows/ci.yml
- README.md
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Now, when styles are merged, we can run automatic checks. Also, I added a note into README.
You can check how it looks like in CI
* passed https://github.com/jajik/mod_proxy_cluster/actions/runs/4925250133/jobs/8799244223
* failed https://github.com/jajik/mod_proxy_cluster/actions/runs/4925218550/jobs/8799176093
> Run clang-format in CI

- .github/workflows/ci.yml
- native/mod_manager/mod_manager.c
Fix a compilation error (#82) introduced with the new code style. The PR also refactors duplicated functionality.
> Fix switch/case label error, tweak status handling

- README.md
> Add a note to README about applying styles suggestions

- .github/workflows/ci.yml
- .gitignore
- README.md
- native/.clang-format
Resolves https://github.com/modcluster/mod_proxy_cluster/issues/97
> CI: results of the clang-format aren't shown in the logs

- test/native/MODCLUSTER-640/mod_proxy_cluster.conf
- test/native/MODCLUSTER-734/mod_proxy_cluster.conf
Remove the removed slotmem module from test configs.
> Remove slotmem from the test configs

- test/native/MODCLUSTER-734/mod_proxy_cluster.conf
It's good to remove the removed one, but one should not forget about adding the right one... sorry.
> Add missing slotmem include

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Addresses #102 . There are still functions worthy of attention (hence the Draft marking) such as `internal_find_best_byrequests` or `update_workers_lbstatus`.
> Refactor create_worker, minor code tweaks

- .github/workflows/ci.yml
- test/JBCS-1236/testit.sh
- test/MODCLUSTER-640/testit.sh
- test/MODCLUSTER-734/mod_proxy_cluster.conf
- test/MODCLUSTER-734/testit.sh
- test/MODCLUSTER-755/testit.sh
- test/MODCLUSTER-785/testit.sh
- test/basetests.sh
- test/hangingtests.sh
- test/httpd/install.sh
- test/includes/common.sh
- test/maintests.sh
- test/pom.xml
- test/setup-dependencies.sh
- test/testsuite.sh
- test/tomcat/Dockerfile
- test/tomcat/context.xml
This is based on #120 , it adds only the last 4 commits. In those, there is a CI support for running tests and minor tweaks. Once the #120 is merged, I'll change the URL for MPC_CONF to the `main` and then we can merge this too.
> Add basic tests into CI

- .gitignore
- test/includes/common.sh
Doesn't play nice with file extension associations.
> Fix non-standard log file extension to *.log files.

- .github/workflows/ci.yml
- test/includes/common.sh
- test/setup-dependencies.sh
- test/testsuite.sh
- test/tomcat/Dockerfile
- test/tomcat/README.md
> Testsuite: Make tomcat version configurable, add CI basic test for each version, minor tweaks and fixes

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
- test/README.md
- test/httpd/mod_lbmethod_cluster.conf
- test/includes/common.sh
- test/testsuite.sh
And add:
Some docs for it.
Arrange DEBUG and some problem when building images.
> Add mod_lbmethod_cluster.conf.

- .github/workflows/ci.yml
CI builds the docs and creates an artifact with the html.
> ci: Build doxygen docs

- native/mod_proxy_cluster/mod_proxy_cluster.c
There are some tweaks, I removed some unnecessary duplication, and removed once-used variables when it made sense. I also removed the two asserts that I think are unnecessary, but it would be better to double check it, I might miss something.
> mod_proxy_cluster.c: Code tweaks and polishing, removal of two asserts

- native/mod_manager/mod_manager.c
when using mod_lbmethod_cluster.c the shared memory for proxy_worker_shared is in mod_balancer, NOT in our shared memory.
> Fix for issue 163.

- native/common/common.c
> Tweak common.c code, remove some duplication

- native/common/common.c
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
- test/maintests.sh
> Fix compile warnings

- .github/workflows/ci.yml
- test/httpd/Dockerfile
> CI: Upgrade Fedora to 39.

- native/mod_proxy_cluster/mod_proxy_cluster.c
close #184
I removed the two variables that were used only once, but other than that it is what was proposed in #184.
> Add missing check for loaded mod_proxy module

- .github/workflows/ci.yml
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
close #183
close #181
We might consider running tests on trunk... personally, I don't know how big deal it is.
> Add compilation with httpd trunk to CI + fix related build failure

- test/JBCS-1236/testit.sh
- test/includes/common.sh
- test/tomcat/Dockerfile
- test/tomcat/context.xml
- test/tomcat/server.xml
- test/tomcat/start.sh
close #188 
I would also consider closing #149
> Testsuite: Add support for specifying whole addresses for tomcat and proxy

- native/include/node.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
close #179 
Also, this will require updating apidocs.
> Record presence/absence of workers within node (#179)

- native/mod_proxy_cluster/mod_proxy_cluster.c
Functions `ap_proxygetline` and `ap_proxy_make_fake_req` that were copied from mod_proxy were removed, because they are no longer needed. They were replaced with explicit bucket API calls. I tried to clear the code a bit.
close #201
> Drop ap_proxygetline, ap_proxy_make_fake_req, and use buckets directly

- native/mod_proxy_cluster/mod_proxy_cluster.c
A few notes:
* the deallocation should happen only if the check is run on a thread, otherwise the `thread` pointer is `NULL` and the `if` won't execute
* the `default` added should not be necessary, but it won't hurt if something gets redefined (AP_STATEs are only macros...)
* I don't think that set_interval is something we need, please double check me on that
> Tweak watchdog logic, drop set_interval, free allocated memory

- native/mod_manager/mod_manager.c
Additionally, I replaced a custom sort with a built-in sort. Lastly, I renamed some functions that are creating the mod_manager page for better clarity.
> Refactor mod_manager.c a bit, break down some bigger functions

- test/MODCLUSTER-640/mod_proxy_cluster.conf
- test/MODCLUSTER-640/testit.sh
- test/MODCLUSTER-734/mod_proxy_cluster.conf
- test/MODCLUSTER-755/mod_proxy_cluster.conf
- test/MODCLUSTER-785/mod_proxy_cluster.conf
- test/MODCLUSTER-794/mod_proxy_cluster.conf
- test/httpd/mod_lbmethod_cluster.conf
- test/httpd/mod_proxy_cluster.conf
- test/websocket/mod_proxy_cluster.conf
close #212 
Remove unnecessary ifs, unnecessary modules, etc.
> Testsuite: Polish conf files

- native/mod_proxy_cluster/mod_proxy_cluster.c
This PR makes the main `update_workers_lbstatus` function a bit wordier, however, it might be more clear now with the check logic separated. My main motivation was to make (un)locking a bit cleaner.
> Refactor updating worker's lbstatus

- native/include/node.h
- native/mod_manager/mod_manager.c
Use provider instead shared memory directly.
> Use provider for shared version_data

- test/tomcat/Dockerfile
> test: Tweak tomcat Dockerfile

- native/common/common.c
- native/include/common.h
I'm opening this as a draft until we discuss the proposal.
> Cache context finding

- native/include/mod_clustersize.h
ref discussion in https://github.com/modcluster/docs.modcluster.io/pull/200
> Use PROXY_WORKER_MAX_ROUTE_SIZE from mod_proxy for JVMROUTESZ

- native/balancers/mod_lbmethod_cluster.c
- native/common/common.c
- native/include/mod_proxy_cluster.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-508
> MODCLUSTER-508: Add BALANCER_PREFIX_LENGTH macro, replace magic constant

- native/mod_manager/mod_manager.c
https://issues.redhat.com/browse/MODCLUSTER-823
> MODCLUSTER-823: Fix ignored aliases

- .github/workflows/ci.yml
- test/httpd/Dockerfile
> Upgrade httpd to 2.4.60

- .github/workflows/ci.yml
- test/httpd/Dockerfile
> Upgrade to httpd 2.4.61

- .github/workflows/ci.yml
- test/httpd/Dockerfile
- test/pom.xml
draft until Windows distribution becomes available
> test: Update httpd to the latest 2.4.62

- .github/workflows/ci.yml
- test/MODCLUSTER-736/testit.sh
- test/setup-dependencies.sh
- test/testsuite.sh
> ci: Use JDK 17 for runtime + add maven options suitable for CI + replace removing mono step

- .gitignore
A minor change, it's annoying to see it listed all the time.
> Add an auxiliary test file to gitignore

- native/mod_manager/mod_manager.c
There is another unlock five line below which is the correct one.
> Remove a double unlock

- native/mod_manager/mod_manager.c
ref [MODCLUSTER-822](https://issues.redhat.com/browse/MODCLUSTER-822)
This approach abstracts processing of Alias and Context for both APP and CONFIG commands. As a result, Alias for CONFIG is now also case insensitive, but that seems more like the correct behavior...
> MODCLUSTER-822: Decline Contexts and Aliases if lengths are exceeded

- native/include/node.h
- native/mod_manager/mod_manager.c
- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Partly addresses #265, but we still should probe whether the offset is necessary at all.
> Correct the offset computation

- test/pom.xml
- test/testsuite.sh
close #255 
10.1 remains the default version
> test: Add tomcat 11 to the testsuite

- native/mod_manager/mod_manager.c
> Fix off by one error in Alias/Context length check

- native/mod_manager/mod_manager.c
The log was not showing up, this fixes that.
ref https://github.com/modcluster/mod_proxy_cluster/pull/202
> Follow up on MODCLUSTER-551: Fix wrong argument to logging

- native/mod_manager/mod_manager.c
Previously, an app would get merged into an existing vhost only in case the first alias would be already in. So that VHost with alias `test` would be updated for command with `Alias=test,demo` but a new VHost would be created for `Alias=demo,test`.
This PR changes the behavior. Now we go through all provided aliases sequentially, and if one matches, the corresponding VHost gets updated. Otherwise a new one is created.
Resolves [MODCLUSTER-824](https://issues.redhat.com/browse/MODCLUSTER-824)
> Improve handling of overlapping aliases in APP commands

- .github/workflows/ci-ignored-workaround.yml
> ci: Add fake perl-tests job to ignored workaround

- native/advertise/mod_advertise.h
- native/balancers/mod_lbmethod_cluster.c
- native/common/common.c
- native/include/common.h
- native/include/mod_proxy_cluster.h
- native/include/node.h
- native/mod_manager/balancer.c
- native/mod_manager/context.c
- native/mod_manager/domain.c
- native/mod_manager/host.c
- native/mod_manager/mod_manager.c
- native/mod_manager/mod_manager.h
- native/mod_manager/node.c
- native/mod_manager/sessionid.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Limit the amount of headers we're including, rearrange them a little bit. I'm certain that there is still some room for improvement, but that would require some moving of the code, which we may do in the future if needed.
> Rearrange all the header includes

- native/balancers/README.md
- native/mod_manager/mod_manager.c
- test-perl/t/conf/cgi.conf.in
- test-perl/t/conf/extra.conf.in
- test/MODCLUSTER-640/mod_lbmethod_cluster.conf
- test/MODCLUSTER-640/mod_proxy_cluster.conf
- test/MODCLUSTER-734/mod_proxy_cluster.conf
- test/MODCLUSTER-755/mod_lbmethod_cluster.conf
- test/MODCLUSTER-755/mod_proxy_cluster.conf
- test/MODCLUSTER-785/mod_lbmethod_cluster.conf
- test/MODCLUSTER-785/mod_proxy_cluster.conf
- test/MODCLUSTER-794/mod_lbmethod_cluster.conf
- test/MODCLUSTER-794/mod_proxy_cluster.conf
- test/httpd/mod_lbmethod_cluster.conf
- test/httpd/mod_proxy_cluster.conf
- test/websocket/mod_proxy_cluster.conf
https://docs.modcluster.io/#configure-httpd
> Change the example directive to be consistent with the docs

- .github/workflows/ci.yml
- test/httpd/Dockerfile
> Upgrade to httpd 2.4.63

- test/httpd/Containerfile
- test/httpd/run.sh
- test/tomcat/Containerfile
Also "fixed" `ADD`/`COPY` usage.
> test: Tweak test containers, reduce size

- .github/workflows/ci.yml
- test/httpd/Containerfile
The issue with the env variable (in the Containerfile) does not manifest in the testsuite because we're using a default in `httpd_start`, but still.
> Fix ENV variable declaration in the test container, update fedora version to 42, tweak CI
