- native/mod_manager/mod_manager.c
I'm porting this change from 1.3.x into master so that it isn't lost.
> MODCLUSTER-463 converts aliases for a context on -APP message arrival.

- native/mod_manager/mod_manager.c
(cherry picked from commit 2fc87897b4b3901eea274af35439cc85a8ffaa89 legacy modcluster/mod_cluster repository)
See [modcluster/mod_cluster/pull/217](https://github.com/modcluster/mod_cluster/pull/217).
> MODCLUSTER-534 update to MODCLUSTER-435 normalizing balancer name

- native/include/mod_clustersize.h
- native/include/node.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Secret is already supported in the ajp proxy in Apache httpd trunk and 2.4.42 (and JBCS-httpd-2.4.37).
> Fix for https://issues.redhat.com/browse/MODCLUSTER-714

- native/mod_manager/mod_manager.c
mod_manager.c had an issue where it would try to open some .lock files in the manager_child_init function, it wouldn't find them and try to create them but it didn't have the permissions since it was a child process.
I just created the .lock files in the manager_init function so all the child processes could inherit the file descriptors.
EDIT**
Also fixed some problems that mod_manager.c has with shared memories.
It would create a shared memory with apr_shm_create, which if httpd didn't shut down properly was never clean up, as a result when httpd would be started again it would try to apr_shm_create the same file and get file exists error.
Now it tries to create an anonymous shared memory, if the system doesn't support anonymous shared memories it removes the old named shared memory if …
> Fix for mod_manager.c,opening files in children processes and shared memory creation [MODCLUSTER-726][MODCLUSTER-725]

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
In the mapping of the MCMP / are triggering a subrequest to /index.html that forces a call to update_workers_node() for each MCMP messages.
The fix adds a manager_map_to_storage() to prevent other httpd modules to try to map our URL (/ and */).
> Fix for https://issues.redhat.com/browse/MODCLUSTER-755

- native/common/common.c
- native/include/mod_proxy_cluster.h
- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix for https://issues.redhat.com/browse/MODCLUSTER-756
Try to cache the shared memory.
And fix the watchdog logic.
Add CacheShareFor (n seconds) Directive.
> [draft] MODCLUSTER-756 table reads repeated in proxy_cluster_pre_request degrade performance

- native/common/common.c
- native/include/mod_proxy_cluster.h
- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
It also fixes https://issues.redhat.com/browse/MODCLUSTER-762 as it is impossible to test without it.
Adds CacheShareFor to control the cache (0 sec no cache and n sec caches for n seconds).
> Fix for https://issues.redhat.com/browse/MODCLUSTER-756

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-765
> [MODCLUSTER-765] avoid update_workers_node calls per request if using CacheShareFor

- native/mod_manager/mod_manager.c
MemManagerFile directive requires absolute path to directory where runtime data is stored.
The patch allows to have relative paths against ServerRoot.
One can use 'MemManagerFile cache/mod_proxy_cluster' instead 'MemManagerFile /var/cache/httpd/mod_proxy_cluster'. The patch allows current configurations that have absolute path to work as before, while ensuring that relative paths are created inside ServerRoot.
https://issues.redhat.com/browse/MODCLUSTER-760
> Allow MemManagerFile to use ServerRoot relative paths fix for MODCLUSTER-760

- native/mod_proxy_cluster/mod_proxy_cluster.c
Something like:
<Proxy balancer://testAP>
BalancerMember http://localhost:8080/
BalancerMember http://localhost:8081/
</Proxy>
is not supported but no error/warning were used, the fix adds a error message and refuses to start httpd.
> Fix for https://issues.redhat.com/browse/MODCLUSTER-771

- native/mod_proxy_cluster/mod_proxy_cluster.c
https://issues.redhat.com/browse/MODCLUSTER-734
Add ModProxyClusterHCTemplate directive to allow a template health check to be added to each mod_proxy_cluster worker.
The format of the ModProxyClusterHCTemplate is the same than the mod_proxy_hcheck ProxyHCTemplate directive.
> Fix for https://issues.redhat.com/browse/MODCLUSTER-734

- native/mod_proxy_cluster/mod_proxy_cluster.c
There is a typo in the value; instead of `12` there it ought to be `124`.
> Fix wrong constant value comparison

- native/advertise/mod_advertise.c
- native/balancers/mod_lbmethod_cluster.c
- native/common/common.c
- native/mod_cluster_slotmem/mod_sharedmem.c
- native/mod_cluster_slotmem/sharedmem_util.c
- native/mod_manager/balancer.c
- native/mod_manager/context.c
- native/mod_manager/domain.c
- native/mod_manager/host.c
- native/mod_manager/mod_manager.c
- native/mod_manager/node.c
- native/mod_manager/sessionid.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix an error with `-Werror=declaration-after-statement` that was introduced in the previous commit 5a42af51883c14e845c692d022f97525aaa7d2d2
> Fix declaration-after-statement error

- native/advertise/mod_advertise.c
On Fedora 36, running `sh buildconf && ./configure --with-apxs=~/apache/bin/apxs && make` in advertise directory ends with following error:
```
Creating configure ...
configure.in:33: warning: AC_OUTPUT should be used without arguments.
configure.in:33: You should run autoupdate.
checking for Apache httpd installation... APXS is ~/apache/bin/apxs
apxs_support is true
configure: creating ./config.status
config.status: creating Makefile
~/apache//build/libtool --silent --mode=compile gcc  -g -O2 -Wall -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -std=c89 -Werror -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wdeclaration-after-statement -Wpointer-arith -Wformat -Wformat-security -Wunused     -DLINUX -D_REENTRANT -D_GNU_SOURCE -DAP_DEBUG …
```
> Fix mod_advertise compile errors with prototypes flags

- native/mod_manager/mod_manager.c
When running tests, httpd was getting stuck. After investigating I found the cause of the deadlock – locking. This PR removes it.
> Fix double locking in mod_manager

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
replace the file/thread locks by apr_global_mutex_t.
arrange the thread logic to use it only in the blocking part of the health check logic.
basically the watchdog logic prevent the graceful restart of the child processes,
> Use ap_hook_child_stopping() to allow cleaner stop of the watchdog logic + arrange thread logic + use more standard lock()/unlock()

- test/native/tests.sh
Some tweaks. Tests should be  more reliable now (e.g., running them after previously failed run, they will clean the hanging containers at first, and the `jdb` part now works properly).
> Fix wring usage of podman instead of docker, fix jdb usage

- .github/workflows/ci.yml
With an increased turnaround, let's make sure things don't break unintentionally with a CMake smoke build on Fedora 38 for a start.
> CI: add a smoke CMake build on Fedora 38

- native/.clang-format
- native/advertise/mod_advertise.c
- native/advertise/mod_advertise.h
- native/balancers/mod_lbmethod_cluster.c
- native/common/common.c
- native/include/balancer.h
- native/include/context.h
- native/include/domain.h
- native/include/host.h
- native/include/mod_clustersize.h
- native/include/mod_proxy_cluster.h
- native/include/node.h
- native/include/sessionid.h
- native/include/slotmem.h
- native/mod_cluster_slotmem/mod_sharedmem.c
- native/mod_cluster_slotmem/sharedmem_util.c
- native/mod_manager/balancer.c
- native/mod_manager/context.c
- native/mod_manager/domain.c
- native/mod_manager/host.c
- native/mod_manager/mod_manager.c
- native/mod_manager/mod_manager.h
- native/mod_manager/node.c
- native/mod_manager/sessionid.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Related to: https://issues.redhat.com/browse/MODCLUSTER-783
I used `indent` with following options: `-i4 -npsl -di0 -br -nce -d0 -cli0 -npcs -nfc1 -nut -ncs -l120`.
The most of the changes are by `indent` itself, however, I removed some unnecessary parenthesis, inconsistent brackets, and made minor tweaks.
Please, I welcome any feedback.
> Apply style guide similar to httpd's one, tweak code style

- test/native/httpd/install.sh
With recent changes, for tests it is necessary to set MaxConnectionsPerChild so that nodes get removed.
> Set MaxConnectionsPerChild to 16 for tests

- native/advertise/mod_advertise.c
- native/mod_cluster_slotmem/sharedmem_util.c
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix an error with older C standard introduced with style guide.
> Fix C++ style comments error with C89/C90

- .github/workflows/ci.yml
- native/mod_proxy_cluster/mod_proxy_cluster.c
There is difference in compilation between regular `make`/`cmake` and the same with `httpd` configured with `--enable-maintainer-mode` and some additional flags. For example, using C++ style comments is ok unless `httpd` is configured as stated above.
Therefore, I think it would be worth creating an image with httpd configured and compiled.
This Draft PR contains a possible solution (using `quay.io/vchlup/httpd-dev`); it is a draft because I think the image should be within the modcluster namespace/organization, not in mine.
The `Containerfile` I used for the image:
```Containerfile
FROM ubi9/ubi:latest
RUN dnf update -y && dnf install -y git gcc make libtool python3 autoconf libxml2-devel pcre2-devel
RUN cd /usr/include/ && ln -s libxml2/libxml .
RUN git clone …
```
> Add build with httpd in dev mode

- test/native/httpd/install.sh
Our testing httpd image has  a variable `BRANCH` by which one can specify a source branch for mod_proxy_cluster. However, if a branch of the given name does not exist, `git checkout` command fails and tests continue on the default main branch. This can lead to false positive/negative tests results.
This PR changes the behaviour – the script now fails in case the checkout is not successful making the image stop.
> Make httpd's install script fail if branch does not exist

- native/mod_proxy_cluster/mod_proxy_cluster.c
I looked into #63, trying to remove the dead code. It seems that the whole function can be removed without affecting the functionality. Tests in the repository are passing. Also, the described behaviour in JIRA related to the fix that introduced the bug is still not reproducible with this change – the node gets flagged REMOVED with hung JVM (the actual removal then depends on `MaxConnectionsPerChild`).
Please, check that I am not missing something.
> Remove a dead code from mod_proxy_cluster

- .github/workflows/ci.yml
- .gitignore
- native/include/mod_proxy_cluster.h
- native/mod_manager/mod_manager.h
- native/scripts/windows-build.bat
In the past it occurred multiple times that a change was introduced that worked on Linux, but broke build on Windows. Now when we no longer use CI via Jenkins, we have limited ability to catch those changes. This PR adds windows runner (`cmake` using) into the CI.
Also, there is a fix that moves an optional function declaration into the correct file (it caused compilation on windows to fail).
> Add Windows runner into CI

- native/include/mod_proxy_cluster.h
- native/mod_proxy_cluster/mod_proxy_cluster.c
Now, compilation is going to fail in case the version is not supported. In case someone tries to load the module with unsupported version, it won't succeed either.
> Add checks for supported HTTPD version

- test/native/tests.sh
Add a default value for IMG variable so that we are a bit more consistent (also, it is annoying to have to define it every time if one sticks to the recommended value).
> tests: Set IMG variable to default if not defined

- native/mod_manager/mod_manager.h
The function is already declared in other module and we do not implement it. We just use it if it's available – [see](https://github.com/modcluster/mod_proxy_cluster/blob/3811731187f39c8b8ce4c22b896c3c55a3c6425c/native/mod_manager/mod_manager.c#L707).
> Remove duplicate balancer_manage function declaration

- test/includes/common.sh
> test: Add httpd's access_log among test outputs

- .github/workflows/ci.yml
For some reason the current way stopped working (e.g., [here](https://github.com/modcluster/mod_proxy_cluster/actions/runs/5852618025/job/16318039134?pr=137)).
> CI: Change package name for docker

- test/includes/common.sh
- test/tomcat/server.xml
- test/tomcat/start.sh
> Fix tomcat ports overlapping

- .github/workflows/ci.yml
- native/include/mod_proxy_cluster.h
- native/include/node.h
- native/mod_manager/mod_manager.c
- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
- test/JBCS-1236/testit.sh
- test/MODCLUSTER-794/mod_proxy_cluster.conf
- test/MODCLUSTER-794/testit.sh
- test/maintests.sh
- test/testsuite.sh
Fix and  new test for https://issues.redhat.com/browse/MODCLUSTER-794.
~~Add test for https://issues.redhat.com/browse/MODCLUSTER-794.~~
~~This branch is based on #120 so I'm opening this as a draft until it is merged.~~
> MODCLUSTER-794 mod_proxy_cluster gets stuck with 20 nodes

- test/includes/common.sh
- test/testsuite.sh
- test/tomcat/Dockerfile
- test/tomcat/README.md
close #141. Introduces two variables for server.xml and context.xml by which you can control which files will be used. This does not introduces separate files for each supported version as it is not needed now.
> test: Add option to change tomcat conf files

- native/mod_proxy_cluster/mod_proxy_cluster.c
It seems that the assert is not needed. The function now returns `NULL` which causes that the outer loop to continue (line 1728 in `internal_find_best_byrequests`).
> Remove an unnecessary assert

- test/README.md
- test/includes/common.sh
- test/setup-dependencies.sh
- test/testsuite.sh
* add lbmethos + mod_proxy_cluster directly into the testsuite (so it is not needed to run tests separately)
* change naming of the directories for dependencies (so it won't interfere with already checked-out directories for development)
* fix test fail in case access_log is missing
> Testsuite tweaks

- native/mod_manager/mod_manager.c
- native/mod_manager/node.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
The removal of the assert changes the behaviour; instead of an empty response the server returns `500` now. You can check the behaviour by running httpd with mod_proxy_cluster on port `6666` and executing:
```sh
curl localhost:6666 -H "User-Agent: ClusterListener/1.0" -X CONFIG --data "JVMRoute=demo&Type=http"
curl localhost:6666 -H "User-Agent: ClusterListener/1.0" -X CONFIG --data "JVMRoute=test&ttl=300&Type=http"
```
> mod_manager.c: Refactor part of `process_config`, remove one assert

- native/mod_manager/mod_manager.c
This PR is based on #154 and it removes the second `ap_assert(0);`. I separated it so it gets enough attention after the first one gets merged.
>  mod_manager.c: Remove the second assert

- native/balancers/mod_lbmethod_cluster.c
- native/mod_manager/mod_manager.c
- test/httpd/mod_lbmethod_cluster.conf
- test/httpd/mod_proxy_cluster.conf
https://issues.redhat.com/browse/MODCLUSTER-733 + I updated the test configs to reflect the change.
> MODCLUSTER-733

- test/httpd/Dockerfile
It's much more convenient in case you want to log and work within the container.
> test: Set httpd container workid to Apache's root

- test/JBCS-1236/testit.sh
- test/MODCLUSTER-640/testit.sh
- test/MODCLUSTER-734/testit.sh
- test/MODCLUSTER-785/testit.sh
- test/basetests.sh
- test/hangingtests.sh
- test/includes/common.sh
- test/maintests.sh
- test/testsuite.sh
- test/tomcat/Dockerfile
- test/tomcat/server.xml
- test/tomcat/start.sh
> tests: Use `portOffset` in Tomcat containers

- README.md
- native/balancers/mod_lbmethod_cluster.c
- native/common/common.c
- native/include/mod_proxy_cluster.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Two things here
* macro `HAVE_CLUSTER_EX_DEBUG` got moved to the header file where it belongs (that caused formatting to change a bit)
* fix a few warnings when the macro is defined (`int` vs `long` and null balancer)
> Move extra debug macro to the header file, fix logging

- native/common/common.c
- native/include/common.h
- native/mod_proxy_cluster/mod_proxy_cluster.c
Fix for https://issues.redhat.com/browse/MODCLUSTER-801
mod_proxy_cluster returns 404 now instead of 503 when there's no matching context
> Fix for MODCLUSTER-801

- native/mod_manager/mod_manager.c
The warning comes from valgrind and is imho relevant (although the functionality does not change). There is no point in going beyond `'\0'` if present.
> Fix Conditional jump or move depends on uninitialised value(s) warning

- native/mod_proxy_cluster/mod_proxy_cluster.c
Term "load balancing" is two separate words.
> Minor typo fix in LBstatusRecalTime option description.

- test/tomcat/start.sh
The conPort is no longer used. And `bin/catalina.sh` is the right part (see the conf above or WORKDIR in the dockerfile).
> test: Fix wrong path and unnecessary sed for tomcat container

- native/mod_proxy_cluster/mod_proxy_cluster.c
I've found another cases where we log more than necessary. These are special because they can (in some cases) occur frequently and are using notice level which is unfortunate as they are logged even higher levels are specified.
> When logging to a regular file, messages of the level notice cannot be suppressed and thus are always logged. However, this doesn't apply when logging is done using syslog.
from https://httpd.apache.org/docs/2.4/mod/core.html#loglevel
> Tweak LogLevels to prevent logfile flooding

- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
It is equivalent to `AP_MODULE_DECLARE_DATA` used currently with the addition of setting the name of the module for the logs (see [the definition](https://github.com/apache/httpd/blob/21155482135ad2ba8e4bfc547dd6d6a0093d502f/include/http_config.h#L467)).
> Use AP_DECLARE_MODULE macro

- .github/workflows/ci.yml
We only build the project on Windows. That means we might (and we did)  miss errors that would be detected when we would run httpd with mod_proxy_cluster. This PR extends the Windows job and after building mod_proxy_cluster runs it trying two request through `curl`.
I open this as a draft, because it's failing currently (and the error is at our side, without loading mod_proxy_cluster and the second `curl` it works).
> CI: Run httpd with mod_proxy_cluster even on Windows

- native/balancers/README.md
- native/mod_manager/mod_manager.c
- test/MODCLUSTER-640/mod_proxy_cluster.conf
- test/MODCLUSTER-734/mod_proxy_cluster.conf
- test/MODCLUSTER-755/mod_proxy_cluster.conf
- test/MODCLUSTER-785/mod_proxy_cluster.conf
- test/MODCLUSTER-794/mod_proxy_cluster.conf
- test/httpd/mod_lbmethod_cluster.conf
- test/httpd/mod_proxy_cluster.conf
- test/websocket/mod_proxy_cluster.conf
Resolves
https://issues.redhat.com/browse/MODCLUSTER-551
> MODCLUSTER-551 Fix spelling of EnableMCPMReceive option

- test/setup-dependencies.sh
When I tried running the testsuite on a fresh system (ubuntu), I forgot to install `curl`. The testuite then failed because it assumed httpd was not ready, but in reality it was missing `curl`. This PR adds a check for the required commands into the dependencies setup.
> test: Add a dependecy check for used commands

- test/includes/common.sh
- test/pom.xml
- test/testsuite.sh
- test/tomcat/Dockerfile
- test/tomcat/start.sh
- test/websocket/basic.sh
close #226 
Tomcat 10.1 is now the default (as requested by @jfclere ) with some necessary changes made to the tests.
> Testsuite: Drop tomcat 8.5 and make tomcat 10.1 the default

- native/mod_manager/mod_manager.c
After MODCLUSTER-204 fix in #234, I've noticed that there's no warning in case of too long context. This adds one & fixes a small off-by-one in printing.
> Follow up on MODCLUSTER-204

- .github/workflows/ci-ignored-workaround.yml
- .github/workflows/ci.yml
> Ci workaround ignored paths

- native/mod_manager/mod_manager.c
There is already the same assert on line 1430 that will get called anyway.
> Remove duplicate assert

- native/mod_proxy_cluster/mod_proxy_cluster.c
I've noticed there is missing the closing one.
> Fix missing parenthesis in a log message

- native/mod_manager/mod_manager.c
There is `removed = id` statement but `0` is a valid `id`. Therefore for such `id` the code in `if` wouldn't execute.
> Fix handling of marking nodes removed

- test/includes/common.sh
Minor tweak that prevents too many open files error (it doesn't affect our tests, but when you try to stress mod_proxy_cluster using our container, it may have an effect).
> test: Increase file limit for httpd container

- RELEASING.md
> Add RELEASING.md with necessary instructions

- native/common/common.c
I believe the current condition is incorrect, because in case of `balancer-s->name` is shorter than the prefix, it gets included for `node->mess.balancer` even though they don't match.
In combination with #267 it prevents 404 when the node is up but without app (yet).
> Fix condition in find_node_context_host

- native/mod_proxy_cluster/mod_proxy_cluster.c
The current behaviour is suspicious. The call to `ap_proxy_initialize_worker` has basically no effect and without this change the connection to backend fails from time to time (when running perf tests with dynamic worker removal) which causes `all workers in error state` (= 503) even though a corresponding node to the worker is up and running.
> Clear the worker status when reusing cleaned worker

- test/MODCLUSTER-640/testit.sh
- test/MODCLUSTER-734/testit.sh
- test/MODCLUSTER-736/testit.sh
- test/MODCLUSTER-755/testit.sh
- test/MODCLUSTER-785/testit.sh
- test/MODCLUSTER-794/testit.sh
- test/basetests.sh
- test/hangingtests.sh
- test/includes/common.sh
- test/maintests.sh
- test/testsuite.sh
- test/websocket/basic.sh
I got annoyed with the inconsistency & also `tomcat_stop` is useless so I removed it.
> test: Tweak test functions names, drop unnecessary ones

- native/mod_manager/mod_manager.c
Fix the output. Currently, one would get
```
node: [1:1],Balancer: mycluster,JVMRoute: spare,LBGroup: [],Host: localhost,Port: 6666,                           Type: ws,flushpackets: 0,flushwait: 10,ping: 10,smax: -1,ttl: 60,timeout: 0
```
(see the gap before `Type`)
instead of
```
node: [1:1],Balancer: mycluster,JVMRoute: spare,LBGroup: [],Host: localhost,Port: 6666,Type: ws,flushpackets: 0,flushwait: 10,ping: 10,smax: -1,ttl: 60,timeout: 0
```
after the fix.
> Fix mod_manager.c DUMP command output

- native/mod_manager/mod_manager.c
These methods are undocummented, without an implementation, and were never used
> Remove unsupported methods from the codebase

- native/mod_manager/mod_manager.c
id `0` is a valid id, so at line 2485 we would want read by this id. But we want to read by `JVMRoute` instead, so `-1` must be used (`-2` for the default is just an arbitrary value we use to detect any change).
> Fix PING-RSP State field

- native/mod_manager/mod_manager.c
> Simplify and fix CONFIG parameters handling

- native/mod_manager/mod_manager.c
This fixes edge cases where the current solution did not work properly, but it also introduces an equivalence between `yes`/`no` and `on`/`off`. The latter can be changed so that the behavior is the same, but I think it's reasonable...
> Fix and improve handling boolean parameters

- native/mod_manager/mod_manager.c
https://issues.redhat.com/browse/MODCLUSTER-832
> Require Alias and Context for *-APP commands

- native/mod_proxy_cluster/mod_proxy_cluster.c
There is a typo/error in the error message: *for* -> *before*.
> Fix an error message to contain the correct directive name

- test-perl/t/issues/MODCLUSTER-824.t
- test-perl/t/mod_proxy_cluster/manager.t
- test-perl/t/mod_proxy_cluster/messages_ok.t
and tweak the rest to have a clean table after each test...
Note, that these sleeps are needed because it takes some time for a node to disapear (it must go through Node REMOVED phase). I'll try to come up with something more elegant in the future.
> Add a test for MODCLUSTER-824

- .github/workflows/ci-ignored-workaround.yml
- .github/workflows/ci.yml
Well, that's not completely true. The default behaviour is `'**'`, the single `*` does not match branches with `/` in their name. Fortunately, we are all well behaved and don't use such names. :slightly_smiling_face: 
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
> ci: Remove branches '*' when it's the default behaviour

- native/mod_proxy_cluster/mod_proxy_cluster.c
Seems like we have omitted it...
> Add slotmem module among preloaded for mod_proxy_cluster

- .github/workflows/ci.yml
- native/balancers/mod_lbmethod_cluster.c
- test/MODCLUSTER-640/mod_lbmethod_cluster.conf
- test/MODCLUSTER-640/testit.sh
- test/MODCLUSTER-734/testit.sh
- test/MODCLUSTER-736/testit.sh
- test/MODCLUSTER-755/mod_lbmethod_cluster.conf
- test/MODCLUSTER-755/mod_proxy_cluster.conf
- test/MODCLUSTER-755/testit.sh
- test/MODCLUSTER-785/mod_lbmethod_cluster.conf
- test/MODCLUSTER-785/testit.sh
- test/MODCLUSTER-794/mod_lbmethod_cluster.conf
- test/MODCLUSTER-794/testit.sh
- test/testsuite.sh
close #297 
close #298 
This resolves two issues, but given that they are connected it seemed reasonable to do it at once. Test that ought to be run with balancer were unfortunately run with cluster. The testsuite needed a few changes and new conf files for the second module.
> Add `UseNocanon` to mod_lbmethod_cluster, fix testsuite to use the right module

- test/tomcat/server.xml
There is no reason to use non-default values.
> test: Use default configuration for tomcat containers

- native/mod_proxy_cluster/mod_proxy_cluster.c
That prevents the message:
AH00898: URI cannot be parsed: ://:0/ returned by /
> Fix for https://issues.redhat.com/browse/MODCLUSTER-774

- native/mod_proxy_cluster/mod_proxy_cluster.c
Resolves https://issues.redhat.com/browse/MODCLUSTER-852
Based on 1.3.x PR: https://github.com/modcluster/mod_cluster/pull/873
> Add address_ttl and disablereuse initialization for worker

- test/includes/common.sh
Apparently, docker has an issue with Containerfiles unless you specify it with `-f` option. We've started using `podman` internally a few PRs ago, so it does not manifest here in our CI, but on systems with `docker` it doesn't work.
> test: Update *_create functions to use Containerfile explicitly

- .github/workflows/ci.yml
close #321 
The solution uses a new container image (it's [the same one](https://github.com/modcluster/ci.modcluster.io/tree/main/httpd-dev) we already use but with a different version of httpd – 2.4.53). This image will be managed manually as the rebuild is necessary only in case the oldest supported version changes.
edit: Adding link https://quay.io/repository/mod_cluster/ci-httpd-dev?tab=tags
> ci: Run maintainer-mode job on the latest and the oldest supported httpd

- native/balancers/mod_lbmethod_cluster.c
- native/mod_manager/mod_manager.c
The missing sync was the problem I was looking for. However, there are a few additional tweaks.
close #325
> Add missing balancer sync to lbmethod_cluster, minor tweaks

- .github/workflows/ci.yml
GitHub recently added ARM runners.
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
They are still in preview, so they may change in the future, but I guess we can always fix or remove it...
> Run some jobs on ARM runners as well

- native/mod_manager/mod_manager.c
- test-perl/t/issues/GH-issue-329.t
- test-perl/t/mod_proxy_cluster/messages_config_nok.t
This addresses #329 and adds additional tests for it. However, there is an error message change for which I opened #330. (tl;dr This unifies the behaviour of 2.x with 1.3.x but both are inaccurate.)
> Fix handling of duplicite MCMP command parameters 

- native/CMakeLists.txt
- native/advertise/mod_advertise.c
- native/balancers/mod_lbmethod_cluster.c
- native/include/balancer.h
- native/include/context.h
- native/include/domain.h
- native/include/host.h
- native/include/mod_clustersize.h
- native/include/node.h
- native/include/sessionid.h
- native/mod_manager/mod_manager.c
- native/mod_proxy_cluster/mod_proxy_cluster.c
Drops unnecessary variable with a for cycle and adds `-Werror` for cmake.
Because of the latter I had to use `{ .name = NULL }` instead of `{ NULL }` but these are equivalent (if the initializer list is not long enough to cover all the members, they are default-initialized). I would prefer `{ }` instead but that's in `C23` and we support `C89`... so next time :smile: 
close #336
> Fix compile warnings on clang and includes + minor tweaks
